name: Deploy 1.0

on:
  push:
    branches:
      - main
      

jobs:
  deploy:
    runs-on: ubuntu-lastest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy 1.0
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend # Директория, которая будет опубликована (замените на свою)